config/routes.rb
AvailabilityAdmin::Application.routes.draw do
  
  get "home/index"
  root :to => 'home#index'
  # resource
  
  devise_for :users, ActiveAdmin::Devise.config
  
  ActiveAdmin.routes(self)
  
  namespace :api do
    
    resources :spaces, only: [], module: 'spaces' do
      member do
        resources :availability, only: [:index, :create]
      end
    end
    
  end
  
  
end

app/models/availability.rb
class Availability < ActiveRecord::Base
  
  belongs_to :space
  
  validates_presence_of :space_id
  
  scope :from_recent, lambda { order(:sel_date) }
  scope :unavailable, lambda { where(unavailable: true) }
  scope :in_range, lambda { |date_start, date_end| where(sel_date: date_start..date_end) }
  
  def self.create_availabilities(space, date_start, date_end, set_to_available)
    space.availabilities.in_range(date_start, date_end).delete_all
    
    # sel_unavailabilities = []
    sel_unavailabilities = (date_start..date_end).map do |sel_date|
      new space: space, sel_date: sel_date, unavailable: ( ! set_to_available ) unless set_to_available
    end.compact
    
    import sel_unavailabilities
  end
  
end

app/models/space.rb
class Space < ActiveRecord::Base
  
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  has_many :availabilities
  
  def availability(date_start, date_end)
    self.availabilities.from_recent.unavailable.in_range(date_start, date_end)
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  
  
  
end

app/controllers/api/spaces/availability_controller.rb
class Api::Spaces::AvailabilityController < ApiController
  
  before_action :set_service, only: [:index, :create]
  
  def index
    @availability = @avail_service.get_availability or return ajax_error(@avail_service.full_error)
  end
  
  def create
    if @avail_service.set_availability
      ajax_success t("availability.edited")
    else
      ajax_error(@avail_service.full_error)
    end
  end
  
  protected
    
    def set_service
      @avail_service = AvailabilityService.new params
    end
  
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  
  respond_to :json
  before_filter :authenticate_user!
  
  
  protected
  
    def ajax_success(resdata)
      res = { :success => true, :data => resdata }
      res = params[:callback] ? "#{params[:callback]}("+res.to_json+');' : res.to_json
      
      respond_to do |format|
        format.html
        format.js
        format.json { render :json => res }
      end
    end
    
    def ajax_error(e, url_to = root_url)
      respond_to do |format|
        format.html { redirect_to url_to, :flash => { :error => e } }
        format.js
        format.json  { render :json => { :success => false, :message => e.to_s } }
      end
      true
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/spaces/availability.html.haml
#flash_cont

#form-edit-availability.hide{title: "Edit Availability"}
  .popup-contents
    %p Set selected date's availability to

.basic_form.panel
  %h3 Filters
  .panel_contents
    %form#availability_search.filter_form{ "accept-charset" => "UTF-8", action: "#", method: "get" }
      .filter_form_field.filter_date_range
        = hidden_field_tag :space_id, @space.id
        = select_tag(:set_to_available, options_for_select([['Add', 1], ['Remove', 0]], selected: :option ))
        availability between #{text_field_tag :start, nil, id: "date_start"}
        and #{text_field_tag :end, nil, id: "date_end"}
        #{submit_tag "Update calendar"}

#calendar{"data-space-id" => @space.id}

app/views/home/index.html.haml
%h1 Availability Demo
%p= link_to "Enter the admin area", admin_root_path, class: 'admin_area_link'

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    = content_tag :div, msg, :class => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%ul.nav
  %li= link_to 'Home', root_path
  = render 'layouts/navigation_links'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Availability Admin'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Availability Admin'}"}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield